# -*- coding: utf-8 -*-

MEMBER_STATUS_NORMAL = 1
MEMBER_STATUS_UNORMAL = 2

MEMBER_STATUS_LIST = [MEMBER_STATUS_NORMAL, MEMBER_STATUS_UNORMAL]

MALE = 1
FEMALE = 2
OTHER = 3
SEX_LIST = [MALE, FEMALE, OTHER]
